# Generated by Django 5.2.8 on 2025-11-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_feedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('players_needed', models.IntegerField()),
                ('cash_prize', models.CharField(blank=True, max_length=50, null=True)),
                ('chat_link', models.URLField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
