# Generated by Django 5.2.8 on 2025-11-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_scheduledmatch_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmatch',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='scheduledmatch',
            name='match_image',
            field=models.ImageField(blank=True, null=True, upload_to='match_images/'),
        ),
    ]
