# Generated by Django 5.2.8 on 2025-11-25 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_scheduledmatch_contact_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmatch',
            name='joined_players',
            field=models.ManyToManyField(blank=True, related_name='joined_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledmatch',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledmatch',
            name='result',
            field=models.CharField(choices=[('none', 'Not Played'), ('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduledmatch',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
    ]
