# Generated by Django 5.2.8 on 2025-11-26 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_scheduledmatch_joined_players_scheduledmatch_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=150)),
                ('sport', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('color', models.CharField(choices=[('#FFF3B0', 'soft-yellow'), ('#FFD6E7', 'soft-pink'), ('#D6F5D6', 'soft-green'), ('#DCEBFF', 'soft-blue'), ('#F0E6FF', 'soft-purple'), ('#FFF0E0', 'soft-peach')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
